export const HOTEL_INFO = {
  name: 'Hotel Marc',
  tagline: 'Your Home Away from Home in the Queen of Hills',
  phone: '+91-8091280700',
  email: 'shimlahotelmarc@gmail.com',
  address: 'Hotel Marc, Next to Kotshera College, Chaura Maidan, Shimla, Himachal Pradesh 171004',
  checkIn: '12:00 PM',
  checkOut: '12:00 PM',
  whatsappNumber: '918091280700',
  googleMapsUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3418.5!2d77.1685!3d31.1048!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sHotel%20Marc!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
  coordinates: {
    lat: 31.1048,
    lng: 77.1685,
  },
};

export const WHATSAPP_MESSAGES = {
  general: 'Hello! I would like to inquire about Hotel Marc, Shimla.',
  roomAvailability: 'Hello! I would like to inquire about room availability at Hotel Marc, Shimla.',
  booking: 'Hello! I would like to book a room at Hotel Marc, Shimla.',
  dining: 'Hello! I would like to inquire about dining options at Hotel Marc, Shimla.',
  facilities: 'Hello! I would like to know more about the facilities at Hotel Marc, Shimla.',
  attractions: 'Hello! I would like to arrange sightseeing from Hotel Marc, Shimla.',
  contact: 'Hello! I have a question about Hotel Marc, Shimla.',
  pickup: 'Hello! I would like to arrange pickup service from Railway Station/Bus Stand to Hotel Marc, Shimla. Please share the details and charges.',
  packages: (packageName: string) => `Hello! I would like to inquire about the "${packageName}" holiday package from Marc Holidayers.`,
};

export const getWhatsAppLink = (message: string) =>
  `https://wa.me/${HOTEL_INFO.whatsappNumber}?text=${encodeURIComponent(message)}`;

export const WHATSAPP_LINK = getWhatsAppLink(WHATSAPP_MESSAGES.roomAvailability);

export const NAV_LINKS = [
  { name: 'Home', path: '/' },
  { name: 'About Us', path: '/about' },
  { name: 'Rooms & Suites', path: '/rooms' },
  { name: 'Dining', path: '/dining' },
  { name: 'Facilities', path: '/facilities' },
  { name: 'Gallery', path: '/gallery' },
  { name: 'Attractions', path: '/attractions' },
  { name: 'Holiday Packages', path: '/packages' },
  { name: 'Reviews', path: '/reviews' },
  { name: 'Contact', path: '/contact' },
];

export const DISTANCES = [
  { place: 'Shimla Railway Station', distance: '1.6 km', time: '10 min drive' },
  { place: 'Mall Road / The Ridge', distance: '~3 km', time: '10-15 min drive' },
  { place: 'Viceregal Lodge', distance: '1.8 km', time: 'Walking distance' },
  { place: 'State Museum', distance: '750 m', time: 'Walking distance' },
  { place: 'ISBT (New Bus Stand)', distance: '~5 km', time: '15 min drive' },
];

export const ROOMS = [
  {
    id: 'deluxe',
    name: 'Deluxe Room',
    subtitle: 'Comfortable Stay',
    bestFor: 'Couples & Business Travelers',
    description: 'Spacious rooms with enhanced amenities and comfortable interiors for a relaxing experience.',
    amenities: ['Queen-size bed', 'Attached Bathroom', 'LCD TV', 'Intercom', 'Room Service', 'Free Wi-Fi'],
    image: '/new-room-images/deluxe-room/0_1_4_deluxe_room_image.jpg',
    images: [
      '/new-room-images/deluxe-room/0_1_4_deluxe_room_image.jpg',
      '/new-room-images/deluxe-room/0_2_7_deluxe_room_image.jpg',
      '/new-room-images/deluxe-room/0_3_8_deluxe_room_image.jpg',
      '/new-room-images/deluxe-room/0_4_9_deluxe_room_image.jpg',
      '/new-room-images/deluxe-room/0_5_10_deluxe_room_image.jpg',
      '/new-room-images/deluxe-room/5_deluxe_room_image.jpg',
      '/new-room-images/deluxe-room/11_deluxe_room_image.jpg',
    ],
    featured: false,
    originalPrice: 2899,
    price: 2499,
  },
  {
    id: 'super-deluxe',
    name: 'Super Deluxe Room',
    subtitle: 'Valley View',
    bestFor: 'Couples and View Lovers',
    description: 'Our premium offering featuring large windows with sweeping views of the Shimla valley. Spacious interiors with a cozy seating area.',
    amenities: ['King-size bed', 'Valley View', 'Free Wi-Fi', 'Wardrobe', 'LCD TV', 'Tea/Coffee Maker', 'Toiletries'],
    image: '/new-room-images/super-deluxe-room/0_0_6_super_deluxe_room_image.jpg',
    images: [
      '/new-room-images/super-deluxe-room/0_0_6_super_deluxe_room_image.jpg',
      '/new-room-images/super-deluxe-room/0_1_5_super_deluxe_room_image.jpg',
      '/new-room-images/super-deluxe-room/0_3_17_super_deluxe_room_image.jpg',
      '/new-room-images/super-deluxe-room/0_4_10_super_deluxe_room_image.jpg',
      '/new-room-images/super-deluxe-room/7_super_deluxe_room_image.jpg',
      '/new-room-images/super-deluxe-room/8_super_deluxe_room_image.jpg',
      '/new-room-images/super-deluxe-room/9_super_deluxe_room_image.jpg',
      '/new-room-images/super-deluxe-room/11_super_deluxe_room_image.jpg',
    ],
    featured: true,
    originalPrice: 3899,
    price: 2899,
  },
  {
    id: 'family-suite',
    name: 'Family Suite',
    subtitle: 'Spacious Comfort',
    bestFor: 'Families of 4 (2 Adults + 2 Kids)',
    description: 'A spacious unit with two double beds ensuring the whole family stays together comfortably with ample space.',
    amenities: ['Two double beds', 'Ample luggage space', 'Seating area', 'Large bathroom', 'Free Wi-Fi', 'LCD TV'],
    image: '/new-room-images/family-suite/0_0_4_family_room_image.jpg',
    images: [
      '/new-room-images/family-suite/0_0_4_family_room_image.jpg',
      '/new-room-images/family-suite/0_1_2_family_room_image.jpg',
      '/new-room-images/family-suite/1_family_room_image.jpg',
      '/new-room-images/family-suite/3_family_room_image.jpg',
      '/new-room-images/family-suite/5_family_room_image.jpg',
      '/new-room-images/family-suite/6_family_room_image.jpg',
    ],
    featured: false,
    originalPrice: 4899,
    price: 3899,
  },
];

export const FACILITIES = [
  {
    name: 'Free Wi-Fi',
    description: 'High-speed internet access in rooms and public areas',
    icon: 'Wifi',
  },
  {
    name: 'Secure Parking',
    description: 'Safe and free drive-in parking space for guests',
    icon: 'Car',
  },
  {
    name: 'Travel Desk',
    description: 'Arrange sightseeing taxis and pick-up/drop services',
    icon: 'MapPin',
  },
  {
    name: 'Laundry Service',
    description: 'Same-day laundry and dry cleaning available',
    icon: 'Shirt',
  },
  {
    name: 'Doctor on Call',
    description: 'Medical assistance available for emergencies',
    icon: 'Stethoscope',
  },
  {
    name: 'Power Backup',
    description: '24-hour generator backup for uninterrupted stay',
    icon: 'Zap',
  },
  {
    name: 'Open Terrace',
    description: 'Enjoy the beautiful Shimla weather from our terrace',
    icon: 'Sun',
  },
  {
    name: 'Room Service',
    description: '24-hour room service for your convenience',
    icon: 'ConciergeBell',
  },
];

export const ATTRACTIONS = [
  {
    name: 'Viceregal Lodge',
    description: 'Historic British-era building now housing the Indian Institute of Advanced Study. Stunning architecture and gardens.',
    distance: '1.8 km',
    duration: '30 min visit',
    image: '/attractions/local-attractions/viceregal_lodge.jpg',
  },
  {
    name: 'Mall Road & The Ridge',
    description: 'The heart of Shimla with colonial architecture, shops, cafes, and stunning mountain views.',
    distance: '3 km',
    duration: '2-3 hours',
    image: '/attractions/local-attractions/mall_road_anthe_ridge.webp',
  },
  {
    name: 'State Museum',
    description: 'Houses a rich collection of Himachali art, sculptures, and historical artifacts.',
    distance: '750 m',
    duration: '1-2 hours',
    image: '/attractions/local-attractions/state_museum.jpg',
  },
  {
    name: 'Kufri',
    description: 'Popular hill station known for skiing, horse riding, and panoramic Himalayan views.',
    distance: '16 km',
    duration: 'Half day trip',
    image: '/attractions/local-attractions/kufri.webp',
  },
  {
    name: 'Naldehra',
    description: 'Home to India\'s oldest golf course with magnificent deodar forests.',
    distance: '22 km',
    duration: 'Half day trip',
    image: '/attractions/more-places-to-explore/naldehra.webp',
  },
  {
    name: 'Jakhu Temple',
    description: 'Ancient temple dedicated to Lord Hanuman with the world\'s largest Hanuman statue.',
    distance: '5 km',
    duration: '2 hours',
    image: '/attractions/more-places-to-explore/shimla_jakhu_temple.jpg',
  },
  {
    name: 'Christ Church',
    description: 'Second oldest church in North India with beautiful stained glass windows.',
    distance: '3 km',
    duration: '30 min visit',
    image: '/attractions/more-places-to-explore/christ-church-shimla.jpg',
  },
  {
    name: 'Chail',
    description: 'Former summer capital of Patiala with the world\'s highest cricket ground.',
    distance: '45 km',
    duration: 'Full day trip',
    image: '/attractions/more-places-to-explore/chail.jpg',
  },
];

export const TESTIMONIALS = [
  {
    name: 'Soumitra Hirlekar',
    review: 'A little off from the hustle bustle of Shimla but good connectivity provided from the hotel itself. The rooms are spotlessly clean and overall service is good. I would recommend it to everyone and take the room with the view - it\'s quite spectacular.',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Sandeep Sharma',
    review: 'Nice hotel and hygienic. Very cooperative staff and delicious food quality. The team guides very well for HP tourism. Thanks Hotel Marc Team Shimla!',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Ketan Mehta',
    review: 'It was a good stay! The food was excellent and the staff superb! There was a staff member who was particularly helpful. Really looking forward to dropping down here again in future.',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Amit Sharma',
    review: 'The hotel is small in size but amazingly maintained. You will get anything you want by them in their service. Mr. Rajesh is very polite and courteous to provide you the best services. Overall big Yes from me.',
    rating: 5,
    source: 'Goibibo',
  },
];

export const ALL_FIVE_STAR_REVIEWS = [
  {
    name: 'Soumitra Hirlekar',
    review: 'A little off from the hustle bustle of Shimla but good connectivity provided from the hotel itself. The rooms are spotlessly clean and overall service is good. I would recommend it to everyone and take the room with the view - it\'s quite spectacular.',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Amit Sharma',
    review: 'The hotel is small in size but amazingly maintained. You will get anything you want by them in their service. Mr. Rajesh is very polite and courteous to provide you the best services. Slight far from mall road but okay for me as you will enjoy trekking and natural beauty here. Overall big Yes from me.',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Pooja Priyadarshi',
    review: 'The Hotel was very good. Very nice service. Very cooperative staff. Mr. Dev and Mr. Sagar were very helpful. Service was good and nice rooms and restaurant. Good food. Thank you Hotel Marc for making my trip very good!',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Govind Bhat',
    review: 'Service quality is good, food is good, amenities extremely good, cleanliness is to my expectation. Only drawback is the location - it took some time to find the hotel due to the hilly roads of Shimla.',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Ketan Mehta',
    review: 'It was a good stay! The food was excellent and the staff superb! There was a staff member who was particularly helpful. Really looking forward to dropping down here again in future.',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Sandeep Sharma',
    review: 'Nice hotel and hygienic. Very cooperative staff and delicious food quality. Mr. Abhishek\'s nature is very nice and guides very well for HP tourism. Thanks Hotel Marc Team Shimla!',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Rohan Verma',
    review: 'Very good staff, very supportive. Manager is well behaved. Nice budget hotel, a bit far but they give pick and drop. Overall very nice experience.',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Sangeetha Bhat',
    review: 'The rooms are small but very very neatly maintained. The approach road is very confusing. Took time to find the place, but still worth it.',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Anurag Thakur',
    review: 'Good hotel and food. Parking available. Near to HP Vidhan Sabha and Chaura Maidan. Good discounts available.',
    rating: 5,
    source: 'Goibibo',
  },
  {
    name: 'Vincent S',
    review: 'Everything was good about this hotel. In this hotel you will find one of the best hotel rooms. Staff is excellent. Food quality and quantity excellent. Good location; near by Mall Road. Overall very good experience.',
    rating: 5,
    source: 'TripAdvisor',
  },
  {
    name: 'Joel J',
    review: 'We visited Hotel Marc on 4th June. Our stay was wonderful as the manager and people made us feel at home. They have awesome food which was a rarity in Shimla. They ensured we received everything. Thank you!',
    rating: 5,
    source: 'TripAdvisor',
  },
  {
    name: 'Raju T',
    review: 'This hotel is very good. Staff are great too. The hotel has car parking. Room is very clean. There is a half-hour walk to Mall Road. I advise everyone that when you go to Shimla then book this hotel. I am so grateful that I chose Hotel Marc.',
    rating: 5,
    source: 'TripAdvisor',
  },
  {
    name: 'Saurabh M',
    review: 'Great place to stay in Shimla. Hotel has a restaurant in Mall Road which is excellent. Parking facility, drop and pick up, great view of the valley. Really quiet place to spend your weekend getaway.',
    rating: 5,
    source: 'TripAdvisor',
  },
  {
    name: 'MayuShinde',
    review: 'Would recommend this hotel for families. All the basic requirements available. Clean and big bedrooms. Clean washroom. Restaurant available. Near to the station. Helpful staff. Food quality served too good. About the hotel - it\'s peaceful and good for people on budget.',
    rating: 5,
    source: 'TripAdvisor',
  },
  {
    name: 'Madapusimukundan',
    review: 'This is a very good hotel for a family and is about 15 minutes drive from The Mall Road. The hotel staff are very courteous. We reached Shimla very late, still could get food at 10:30 PM! We were very happy with our stay!',
    rating: 5,
    source: 'TripAdvisor',
  },
  {
    name: 'Guest User',
    review: 'Nice stay. Staff was very courteous. Food was homely. Service excellent. Location good. Amenities excellent.',
    rating: 5,
    source: 'Trip.com',
  },
];

export const GOOGLE_REVIEWS_URL = 'https://www.google.com/travel/search?q=hotel%20marc%20shimla&g2lb=4965990%2C72317059%2C72414906%2C72471280%2C72485658%2C72560029%2C72573224%2C72647020%2C72686036%2C72803964%2C72882230%2C72958624%2C73059275%2C73064764%2C73107089%2C73192290&hl=en-IN&gl=in&ssta=1&ts=CAESCgoCCAMKAggDEAAaHhIcEhQKBwjqDxABGA0SBwjqDxABGA4YATIECAAQACoHCgU6A0lOUg&qs=CAEyFENnc0l4TVhIMXZHd3U3N0VBUkFCOAhCCRHp8xI2xK6AmkIJEb_3Dxnw-vMC&ap=aAG6AQdyZXZpZXdz&ictx=111';

export const IMAGES = {
  hero: '/facade1.jpg',
  heroAbout: '/facade1.jpg',
  heroRooms: '/new-room-images/super-deluxe-room/0_0_6_super_deluxe_room_image.jpg',
  heroDining: '/dining/hotel-marc-shimla-banner.webp',
  heroFacilities: '/facility/facilities-banner.jpg',
  heroContact: '/view1.jpg',
  heroAttractions: '/attractions/banner.jpeg',
  heroPackages: '/package-images/holidays-package-hero.jpg',
  shimlaValley: '/view1.jpg',
  hotelExterior: '/facade1.jpg',
  dining: '/rest1.jpg',
  terrace: '/room1.jpg',
};

export const MARC_HOLIDAYERS = {
  name: 'Marc Holidayers',
  tagline: 'A Travel Concept by Hotel Marc, Himachal Pradesh',
  registrationNo: '11-2415/2025-DTO-SML',
  approvedBy: 'Himachal Tourism',
  phone: '+91-8091280700',
  altPhone: '+91-9418385000',
  email: 'shimlahotelmarc@gmail.com',
};

export interface PackageDay {
  day: number;
  title: string;
  description: string;
  highlights: string[];
  meals: string;
  overnight: string;
}

export interface HolidayPackage {
  id: string;
  name: string;
  duration: string;
  nights: number;
  days: number;
  tagline: string;
  description: string;
  pickupDrop: string;
  transportation: string;
  accommodation: string;
  mealPlan: string;
  image: string;
  itinerary: PackageDay[];
  inclusions: string[];
  exclusions: string[];
  optionalExcursions?: string[];
  badge?: 'popular' | 'bestValue' | 'new';
}

export const HOLIDAY_PACKAGES: HolidayPackage[] = [
  {
    id: 'shimla-kullu-manali',
    name: 'Shimla - Kullu - Manali',
    duration: '5N/6D',
    nights: 5,
    days: 6,
    tagline: 'Special Holiday Package',
    description: 'Experience the best of Himachal Pradesh with this comprehensive tour covering Shimla, Kullu, and Manali. From colonial charm to adventure sports, this package has it all.',
    pickupDrop: 'Delhi - Delhi',
    transportation: 'Private Sedan',
    accommodation: '1 Deluxe Room',
    mealPlan: 'Breakfast & Dinner (Veg)',
    image: '/package-images/shimla-kulu-manali.webp',
    badge: 'popular',
    itinerary: [
      {
        day: 1,
        title: 'Delhi to Shimla',
        description: 'Arrival at Delhi Airport/Railway Station. Meet our representative and proceed towards Shimla by private cab. On arrival, check-in at the hotel and relax.',
        highlights: [],
        meals: 'Dinner',
        overnight: 'Shimla',
      },
      {
        day: 2,
        title: 'Kufri & Local Shimla Sightseeing',
        description: 'After breakfast, proceed for a full-day excursion to Kufri, a beautiful hill station located at an altitude of 2,622 meters. En route visit Green Valley. Enjoy optional activities like Yak Ride, Horse Ride, Mini Zoo, Fun World, Haunted House, etc. In the evening, enjoy Local Shimla Sightseeing.',
        highlights: ['Mall Road', 'Ridge', 'Lakkar Market', 'Scandal Point', 'Christ Church', 'Kali Bari Temple'],
        meals: 'Breakfast & Dinner',
        overnight: 'Shimla',
      },
      {
        day: 3,
        title: 'Shimla to Kullu - Manali',
        description: 'After breakfast, check-out and proceed towards Manali. En-route sightseeing includes beautiful stops along the way.',
        highlights: ['Sunder Nagar Lake', 'Pandoh Dam', 'Hanogi Mata Temple', 'Kullu Shopping Point', 'Kullu River Rafting Point'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 4,
        title: 'Manali Local Sightseeing',
        description: 'After breakfast, enjoy full-day Manali sightseeing covering the most iconic attractions.',
        highlights: ['Hadimba Devi Temple', 'Vashisht Temple & Hot Water Springs', 'Tibetan Monastery', 'Club House', 'Van Vihar'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 5,
        title: 'Solang Valley - Atal Tunnel - Sissu',
        description: 'After breakfast, proceed to Solang Valley, famous for adventure activities like Paragliding, Zorbing, Ropeway / Gondola Ride. Later visit Atal Tunnel and beautiful Sissu Village.',
        highlights: ['Solang Valley', 'Atal Tunnel', 'Sissu Village'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 6,
        title: 'Manali to Delhi',
        description: 'After breakfast, check-out and drive back to Delhi with sweet memories of the tour.',
        highlights: [],
        meals: 'Breakfast',
        overnight: '',
      },
    ],
    inclusions: [
      'Private Sedan Cab (Delhi-Shimla-Manali-Delhi)',
      '05 Nights hotel accommodation',
      'Daily Breakfast & Dinner (MAP Plan)',
      'All sightseeing as per itinerary',
      'Toll Tax, Parking, Green Tax',
      'Driver Allowance & Fuel',
      'Pick-up & Drop from Delhi',
    ],
    exclusions: [
      'Guide charges',
      'Heater charges (if applicable)',
      'Camera / Monument fees',
      'Adventure activities (Rafting, Paragliding, etc.)',
      'Personal expenses & extra meals',
    ],
    optionalExcursions: ['Kasol', 'Manikaran Sahib'],
  },
  {
    id: 'special-shimla',
    name: 'Special Shimla',
    duration: '2N/3D',
    nights: 2,
    days: 3,
    tagline: 'Quick Shimla Getaway',
    description: 'A perfect short escape to the Queen of Hills. Explore the colonial charm of Shimla with this compact yet fulfilling package.',
    pickupDrop: 'Delhi - Delhi',
    transportation: 'Private Sedan',
    accommodation: '1 Deluxe Room',
    mealPlan: 'Breakfast & Dinner (Veg)',
    image: '/package-images/special-Shimla.jpg',
    itinerary: [
      {
        day: 1,
        title: 'Delhi to Shimla',
        description: 'Depart from Delhi early morning. Scenic drive through the hills. Arrive Shimla by evening, check-in and relax.',
        highlights: [],
        meals: 'Dinner',
        overnight: 'Shimla',
      },
      {
        day: 2,
        title: 'Shimla & Kufri Sightseeing',
        description: 'Full day exploring Shimla and Kufri. Visit Mall Road, Ridge, Christ Church, and enjoy the mountain views at Kufri.',
        highlights: ['Mall Road', 'The Ridge', 'Christ Church', 'Kufri', 'Green Valley', 'Lakkar Bazaar'],
        meals: 'Breakfast & Dinner',
        overnight: 'Shimla',
      },
      {
        day: 3,
        title: 'Shimla to Delhi',
        description: 'After breakfast, check-out and drive back to Delhi with wonderful memories.',
        highlights: [],
        meals: 'Breakfast',
        overnight: '',
      },
    ],
    inclusions: [
      'Private Sedan Cab (Delhi-Shimla-Delhi)',
      '02 Nights hotel accommodation',
      'Daily Breakfast & Dinner (MAP Plan)',
      'All sightseeing as per itinerary',
      'Toll Tax, Parking, Green Tax',
      'Driver Allowance & Fuel',
    ],
    exclusions: [
      'Guide charges',
      'Heater charges (if applicable)',
      'Adventure activities at Kufri',
      'Personal expenses & extra meals',
    ],
  },
  {
    id: 'unforgettable-shimla',
    name: 'Unforgettable Shimla',
    duration: '3N/4D',
    nights: 3,
    days: 4,
    tagline: 'Extended Shimla Experience',
    description: 'Dive deeper into Shimla\'s beauty with this extended package. Explore hidden gems, nearby attractions, and experience the true essence of this hill station.',
    pickupDrop: 'Delhi - Delhi',
    transportation: 'Private Sedan',
    accommodation: '1 Deluxe Room',
    mealPlan: 'Breakfast & Dinner (Veg)',
    image: '/package-images/Unforgettable-Shimla.jpg',
    badge: 'bestValue',
    itinerary: [
      {
        day: 1,
        title: 'Delhi to Shimla',
        description: 'Morning departure from Delhi. Scenic drive through Chandigarh and the winding mountain roads. Evening arrival in Shimla.',
        highlights: [],
        meals: 'Dinner',
        overnight: 'Shimla',
      },
      {
        day: 2,
        title: 'Local Shimla Sightseeing',
        description: 'Explore the heart of Shimla including its famous landmarks and colonial heritage sites.',
        highlights: ['Mall Road', 'The Ridge', 'Christ Church', 'Scandal Point', 'Gaiety Theatre', 'State Museum'],
        meals: 'Breakfast & Dinner',
        overnight: 'Shimla',
      },
      {
        day: 3,
        title: 'Kufri & Naldehra Excursion',
        description: 'Day trip to Kufri for adventure activities and Naldehra for its serene golf course and cedar forests.',
        highlights: ['Kufri', 'Green Valley', 'Naldehra Golf Course', 'Mahunag Temple'],
        meals: 'Breakfast & Dinner',
        overnight: 'Shimla',
      },
      {
        day: 4,
        title: 'Shimla to Delhi',
        description: 'After a leisurely breakfast, check-out and return to Delhi.',
        highlights: [],
        meals: 'Breakfast',
        overnight: '',
      },
    ],
    inclusions: [
      'Private Sedan Cab (Delhi-Shimla-Delhi)',
      '03 Nights hotel accommodation',
      'Daily Breakfast & Dinner (MAP Plan)',
      'All sightseeing as per itinerary',
      'Toll Tax, Parking, Green Tax',
      'Driver Allowance & Fuel',
    ],
    exclusions: [
      'Guide charges',
      'Heater charges (if applicable)',
      'Adventure activities',
      'Golf course green fees',
      'Personal expenses & extra meals',
    ],
  },
  {
    id: 'manali-package',
    name: 'Manali Package',
    duration: '2N/3D',
    nights: 2,
    days: 3,
    tagline: 'Adventure Awaits',
    description: 'A quick adventure-packed trip to Manali. Perfect for thrill-seekers and nature lovers looking for a short mountain escape.',
    pickupDrop: 'Delhi - Delhi',
    transportation: 'Private Sedan',
    accommodation: '1 Deluxe Room',
    mealPlan: 'Breakfast & Dinner (Veg)',
    image: '/package-images/manali-package.jpg',
    itinerary: [
      {
        day: 1,
        title: 'Delhi to Manali',
        description: 'Overnight journey from Delhi to Manali. Scenic drive through the mountains.',
        highlights: [],
        meals: 'Dinner (on arrival)',
        overnight: 'Manali',
      },
      {
        day: 2,
        title: 'Manali Sightseeing & Solang Valley',
        description: 'Full day exploring Manali attractions and Solang Valley for adventure activities.',
        highlights: ['Hadimba Temple', 'Vashisht Hot Springs', 'Mall Road', 'Solang Valley', 'Tibetan Monastery'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 3,
        title: 'Manali to Delhi',
        description: 'After breakfast, begin return journey to Delhi with beautiful memories.',
        highlights: [],
        meals: 'Breakfast',
        overnight: '',
      },
    ],
    inclusions: [
      'Private Sedan Cab (Delhi-Manali-Delhi)',
      '02 Nights hotel accommodation',
      'Daily Breakfast & Dinner (MAP Plan)',
      'All sightseeing as per itinerary',
      'Toll Tax, Parking, Green Tax',
      'Driver Allowance & Fuel',
    ],
    exclusions: [
      'Guide charges',
      'Heater charges (if applicable)',
      'Adventure activities (Paragliding, Zorbing, etc.)',
      'Personal expenses & extra meals',
    ],
  },
  {
    id: 'kullu-manali',
    name: 'Kullu Manali',
    duration: '3N/4D',
    nights: 3,
    days: 4,
    tagline: 'Valley of Gods',
    description: 'Explore the enchanting Kullu Valley and vibrant Manali. River rafting, temple visits, and mountain adventures await.',
    pickupDrop: 'Delhi - Delhi',
    transportation: 'Private Sedan',
    accommodation: '1 Deluxe Room',
    mealPlan: 'Breakfast & Dinner (Veg)',
    image: '/package-images/kullu_manali.jpg',
    itinerary: [
      {
        day: 1,
        title: 'Delhi to Kullu/Manali',
        description: 'Depart from Delhi and drive towards Kullu Valley. En-route enjoy the scenic beauty of the mountains.',
        highlights: ['Pandoh Dam', 'Kullu Valley views'],
        meals: 'Dinner',
        overnight: 'Manali',
      },
      {
        day: 2,
        title: 'Manali Local Sightseeing',
        description: 'Explore the cultural and natural attractions of Manali.',
        highlights: ['Hadimba Devi Temple', 'Manu Temple', 'Vashisht Temple', 'Club House', 'Tibetan Monastery', 'Van Vihar'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 3,
        title: 'Solang Valley & Atal Tunnel',
        description: 'Adventure day at Solang Valley followed by visit to the engineering marvel Atal Tunnel and Sissu.',
        highlights: ['Solang Valley', 'Atal Tunnel', 'Sissu Village', 'Adventure activities'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 4,
        title: 'Manali to Delhi',
        description: 'After breakfast, check-out and drive back to Delhi. Optional stop at Kullu for shopping.',
        highlights: ['Kullu Shawl Shopping'],
        meals: 'Breakfast',
        overnight: '',
      },
    ],
    inclusions: [
      'Private Sedan Cab (Delhi-Manali-Delhi)',
      '03 Nights hotel accommodation',
      'Daily Breakfast & Dinner (MAP Plan)',
      'All sightseeing as per itinerary',
      'Toll Tax, Parking, Green Tax',
      'Driver Allowance & Fuel',
    ],
    exclusions: [
      'Guide charges',
      'Heater charges (if applicable)',
      'Adventure activities',
      'River rafting',
      'Personal expenses & extra meals',
    ],
    optionalExcursions: ['Kasol', 'Manikaran Sahib'],
  },
  {
    id: 'shimla-manali',
    name: 'Shimla Manali',
    duration: '4N/5D',
    nights: 4,
    days: 5,
    tagline: 'Best of Both Worlds',
    description: 'The perfect combination of Shimla\'s colonial elegance and Manali\'s adventurous spirit. A balanced tour for all travelers.',
    pickupDrop: 'Delhi - Delhi',
    transportation: 'Private Sedan',
    accommodation: '1 Deluxe Room',
    mealPlan: 'Breakfast & Dinner (Veg)',
    image: '/package-images/shimla-manali.png',
    itinerary: [
      {
        day: 1,
        title: 'Delhi to Shimla',
        description: 'Depart from Delhi and drive to Shimla. Check-in and evening at leisure to explore Mall Road.',
        highlights: ['Mall Road evening walk'],
        meals: 'Dinner',
        overnight: 'Shimla',
      },
      {
        day: 2,
        title: 'Shimla & Kufri Sightseeing',
        description: 'Full day exploring Shimla\'s landmarks and Kufri\'s natural beauty.',
        highlights: ['The Ridge', 'Christ Church', 'Kufri', 'Green Valley', 'Jakhu Temple'],
        meals: 'Breakfast & Dinner',
        overnight: 'Shimla',
      },
      {
        day: 3,
        title: 'Shimla to Manali',
        description: 'Scenic drive from Shimla to Manali through the mountains. En-route sightseeing.',
        highlights: ['Sundernagar Lake', 'Pandoh Dam', 'Kullu Valley'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 4,
        title: 'Manali Sightseeing & Solang Valley',
        description: 'Explore Manali attractions and enjoy adventure activities at Solang Valley.',
        highlights: ['Hadimba Temple', 'Solang Valley', 'Atal Tunnel', 'Old Manali'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 5,
        title: 'Manali to Delhi',
        description: 'After breakfast, begin the return journey to Delhi.',
        highlights: [],
        meals: 'Breakfast',
        overnight: '',
      },
    ],
    inclusions: [
      'Private Sedan Cab (Delhi-Shimla-Manali-Delhi)',
      '04 Nights hotel accommodation',
      'Daily Breakfast & Dinner (MAP Plan)',
      'All sightseeing as per itinerary',
      'Toll Tax, Parking, Green Tax',
      'Driver Allowance & Fuel',
    ],
    exclusions: [
      'Guide charges',
      'Heater charges (if applicable)',
      'Adventure activities',
      'Personal expenses & extra meals',
    ],
  },
  {
    id: 'complete-shimla-kullu-manali',
    name: 'Shimla Kullu Manali',
    duration: '5N/6D',
    nights: 5,
    days: 6,
    tagline: 'Complete Himachal Experience',
    description: 'A comprehensive tour covering Shimla, Kullu, and Manali with ample time to explore each destination thoroughly.',
    pickupDrop: 'Delhi - Delhi',
    transportation: 'Private Sedan',
    accommodation: '1 Deluxe Room',
    mealPlan: 'Breakfast & Dinner (Veg)',
    image: '/package-images/shimla-kulu-manali2.webp',
    itinerary: [
      {
        day: 1,
        title: 'Delhi to Shimla',
        description: 'Morning departure from Delhi. Arrive Shimla by evening and check-in.',
        highlights: [],
        meals: 'Dinner',
        overnight: 'Shimla',
      },
      {
        day: 2,
        title: 'Shimla Sightseeing',
        description: 'Full day exploring Shimla including Kufri excursion.',
        highlights: ['Kufri', 'Green Valley', 'Mall Road', 'Ridge', 'Christ Church', 'Scandal Point'],
        meals: 'Breakfast & Dinner',
        overnight: 'Shimla',
      },
      {
        day: 3,
        title: 'Shimla to Kullu to Manali',
        description: 'Drive to Manali via Kullu Valley with sightseeing stops.',
        highlights: ['Sundernagar Lake', 'Pandoh Dam', 'Hanogi Mata Temple', 'Kullu River Point'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 4,
        title: 'Manali Local Sightseeing',
        description: 'Explore Manali\'s temples, monasteries, and natural attractions.',
        highlights: ['Hadimba Temple', 'Vashisht Hot Springs', 'Tibetan Monastery', 'Club House', 'Van Vihar'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 5,
        title: 'Solang Valley & Atal Tunnel',
        description: 'Adventure day at Solang Valley and visit to Atal Tunnel and Sissu.',
        highlights: ['Solang Valley', 'Atal Tunnel', 'Sissu Village'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 6,
        title: 'Manali to Delhi',
        description: 'After breakfast, drive back to Delhi with sweet memories.',
        highlights: [],
        meals: 'Breakfast',
        overnight: '',
      },
    ],
    inclusions: [
      'Private Sedan Cab (Delhi-Shimla-Manali-Delhi)',
      '05 Nights hotel accommodation',
      'Daily Breakfast & Dinner (MAP Plan)',
      'All sightseeing as per itinerary',
      'Toll Tax, Parking, Green Tax',
      'Driver Allowance & Fuel',
    ],
    exclusions: [
      'Guide charges',
      'Heater charges (if applicable)',
      'Adventure activities',
      'Personal expenses & extra meals',
    ],
    optionalExcursions: ['Kasol', 'Manikaran Sahib'],
  },
  {
    id: 'heaven-himachal',
    name: 'Heaven Himachal',
    duration: '8N/9D',
    nights: 8,
    days: 9,
    tagline: 'The Ultimate Himachal Journey',
    description: 'The most comprehensive Himachal Pradesh tour. From Shimla to Manali to Dharamshala, experience the diverse beauty and culture of the Himalayan state.',
    pickupDrop: 'Delhi - Delhi',
    transportation: 'Private Sedan',
    accommodation: '1 Deluxe Room',
    mealPlan: 'Breakfast & Dinner (Veg)',
    image: '/package-images/heaven-himachal.webp',
    badge: 'new',
    itinerary: [
      {
        day: 1,
        title: 'Delhi to Shimla',
        description: 'Depart from Delhi and drive to Shimla. Evening free for Mall Road exploration.',
        highlights: ['Mall Road'],
        meals: 'Dinner',
        overnight: 'Shimla',
      },
      {
        day: 2,
        title: 'Shimla Sightseeing',
        description: 'Full day exploring Shimla and Kufri.',
        highlights: ['Kufri', 'Green Valley', 'The Ridge', 'Christ Church', 'Jakhu Temple'],
        meals: 'Breakfast & Dinner',
        overnight: 'Shimla',
      },
      {
        day: 3,
        title: 'Shimla to Manali',
        description: 'Scenic drive to Manali via Kullu Valley.',
        highlights: ['Sundernagar Lake', 'Pandoh Dam', 'Kullu Valley'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 4,
        title: 'Manali Local Sightseeing',
        description: 'Explore Manali\'s famous attractions.',
        highlights: ['Hadimba Temple', 'Vashisht', 'Tibetan Monastery', 'Old Manali'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 5,
        title: 'Solang Valley & Atal Tunnel',
        description: 'Adventure at Solang Valley and visit Atal Tunnel.',
        highlights: ['Solang Valley', 'Atal Tunnel', 'Sissu Village'],
        meals: 'Breakfast & Dinner',
        overnight: 'Manali',
      },
      {
        day: 6,
        title: 'Manali to Dharamshala',
        description: 'Drive to Dharamshala, the home of Dalai Lama.',
        highlights: ['Scenic mountain drive'],
        meals: 'Breakfast & Dinner',
        overnight: 'Dharamshala',
      },
      {
        day: 7,
        title: 'Dharamshala & McLeodganj',
        description: 'Explore Dharamshala, McLeodganj, and Tibetan culture.',
        highlights: ['Dalai Lama Temple', 'Bhagsu Waterfall', 'McLeodganj Market', 'Namgyal Monastery'],
        meals: 'Breakfast & Dinner',
        overnight: 'Dharamshala',
      },
      {
        day: 8,
        title: 'Dharamshala to Amritsar/Chandigarh',
        description: 'Drive to Amritsar or Chandigarh for overnight stay.',
        highlights: ['Golden Temple (if Amritsar)', 'Rock Garden (if Chandigarh)'],
        meals: 'Breakfast & Dinner',
        overnight: 'Amritsar/Chandigarh',
      },
      {
        day: 9,
        title: 'Return to Delhi',
        description: 'After breakfast, drive back to Delhi.',
        highlights: [],
        meals: 'Breakfast',
        overnight: '',
      },
    ],
    inclusions: [
      'Private Sedan Cab for entire tour',
      '08 Nights hotel accommodation',
      'Daily Breakfast & Dinner (MAP Plan)',
      'All sightseeing as per itinerary',
      'Toll Tax, Parking, Green Tax',
      'Driver Allowance & Fuel',
    ],
    exclusions: [
      'Guide charges',
      'Heater charges (if applicable)',
      'Adventure activities',
      'Monument entry fees',
      'Personal expenses & extra meals',
    ],
    optionalExcursions: ['Kasol', 'Manikaran Sahib', 'Triund Trek'],
  },
  {
    id: 'devi-darshan',
    name: 'Devi Darshan',
    duration: '3N/4D',
    nights: 3,
    days: 4,
    tagline: 'Sacred Temple Circuit',
    description: 'A spiritual journey to the most revered Devi temples of Himachal Pradesh. Visit the powerful Shakti Peethas and seek divine blessings.',
    pickupDrop: 'Chandigarh - Chandigarh',
    transportation: 'Private Sedan',
    accommodation: '1 Deluxe Room',
    mealPlan: 'Breakfast & Dinner (Veg)',
    image: '/package-images/devi-darshan.jpg',
    itinerary: [
      {
        day: 1,
        title: 'Chandigarh to Naina Devi to Chintpurni',
        description: 'Early morning departure from Chandigarh. Visit Naina Devi Temple in Bilaspur, one of the 51 Shakti Peethas. Later proceed to Chintpurni Temple in Una district.',
        highlights: ['Naina Devi Temple (Bilaspur)', 'Chintpurni Temple (Una)'],
        meals: 'Dinner',
        overnight: 'Near Kangra',
      },
      {
        day: 2,
        title: 'Jwala Devi & Brajeshwari Temple',
        description: 'Morning visit to Jwala Devi Temple, famous for its eternal flames. Later visit Brajeshwari Devi Temple (Kangra Devi), one of the oldest Shakti Peethas.',
        highlights: ['Jwala Devi Temple (Kangra)', 'Brajeshwari/Kangra Devi Temple (Kangra)'],
        meals: 'Breakfast & Dinner',
        overnight: 'Near Kangra',
      },
      {
        day: 3,
        title: 'Chamunda Devi Temple',
        description: 'Visit Chamunda Devi Temple, situated on the banks of Baner River. Spend the day in peaceful darshan and explore the temple surroundings.',
        highlights: ['Chamunda Devi Temple (Kangra)'],
        meals: 'Breakfast & Dinner',
        overnight: 'Near Kangra',
      },
      {
        day: 4,
        title: 'Return to Chandigarh',
        description: 'After breakfast and morning prayers, drive back to Chandigarh with divine blessings.',
        highlights: [],
        meals: 'Breakfast',
        overnight: '',
      },
    ],
    inclusions: [
      'Private Sedan Cab for entire tour',
      '03 Nights hotel accommodation',
      'Daily Breakfast & Dinner (Veg Only)',
      'All temple visits as per itinerary',
      'Toll Tax, Parking',
      'Driver Allowance & Fuel',
    ],
    exclusions: [
      'Prasad and donation at temples',
      'Puja arrangements',
      'Personal expenses',
      'Any meals not mentioned',
    ],
  },
];

export const BOOKING_POLICY = {
  advance: '30% advance required for booking confirmation',
  voucher: '50% payment required for voucher issuance',
  remaining: 'Remaining amount to be paid at hotel check-in',
  cancellation: [
    { period: 'Before 30 days', charge: '10%' },
    { period: 'Before 15 days', charge: '50%' },
    { period: 'Within 15 days', charge: '100%' },
  ],
  terms: [
    'AC will not work in hill areas',
    'Hotel check-in & check-out as per policy',
    'Early check-in / Late check-out subject to availability',
  ],
};
