export { Home } from './Home';
export { About } from './About';
export { Rooms } from './Rooms';
export { Dining } from './Dining';
export { Facilities } from './Facilities';
export { Contact } from './Contact';
export { Attractions } from './Attractions';
export { default as Reviews } from './Reviews';
export { Gallery } from './Gallery';
export { HolidayPackages } from './HolidayPackages';
export { PackageDetail } from './PackageDetail';
